config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :users, only: [:show]

  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :description, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_row.html.erb
<tr>
  <td><%= event.title %></td>
  <td><%= event.location %></td>
  <td><%= event.date %></td>
</tr>

app/views/events/index.html.erb
<h1>Events</h1>
<%= link_to "Create Event", new_event_url %>

<table>
  <thead>
    <th>Title</th>
    <th>Location</th>
    <th>Date</th>
  </thead>
  <tbody>
    <%= render partial: "event_row", collection: @events, as: "event" %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>Create Event</h1>
<%= form_with model: @event, url: events_url do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<div>
  <h1>Event</h1>

  <p>Title: <%= @event.title %></p>

  <p>Description: <%= @event.description %></p>

  <p>Location: <%= @event.location %></p>

  <p>Event date: <%= @event.date %>

  <p>Event creator: <%= link_to @event.creator.email, user_url(@event.creator) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<p><%= @user.email %></p>